### ISSUE TITLE
How did you use the word-smithing scripts?

### ISSUE THREAD

**Issue by codementum** [eamonnmag/dphil-thesis#1]
Like https://github.com/eamonnmag/dphil-thesis/blob/master/check_repeats.sh

Were they built into the build process somehow, or did you run them individually?

(Would be useful for paper-writing!)

**Comment by eamonnmag** [comment]
I used it as is shown here - http://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/

```
# Check style:
echo "weasel words: "
sh weasel chapters/*.tex
echo
echo "passive voice: "
sh passivevoice chapters/*.tex
echo
echo "duplicates: "
perl check_repeats chapters/*.tex
```
